project_id = "ioatqhiqhzumuxivjcon"

[functions.ai-tips]
verify_jwt = false

[functions.ai-copilot-chat]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false